version: '2'
services:
#  web:
#    build: .
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./build:/usr/src/app/target
#    links:
#      - db
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=fileexchangedb
      - POSTGRES_USER=one
      - POSTGRES_PASSWORD=two